### ISSUE TITLE
Multi-line input boxes

### ISSUE THREAD

**Issue by chris-chapin** [Living-Snow-Project/LivingSnowProject#10]
Current TextInput boxes do not grow in height when the text exceeds the width of the box and the user cannot proof their input in full.

**Comment by OtchereDev** [comment]
Description please

**Comment by chris-chapin** [comment]
https://github.com/Living-Snow-Project/LivingSnowProject/commit/f1b4fc2abf8cc895dd624841928424a72adf79b2
